name: progress
description: >
  Compute progress of a long-running process.
version: 0.1.0+1
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/progress.dart

environment:
  sdk: ">=1.22.0 <2.0.0"

dependencies:
  meta: ^1.0.5

dev_dependencies:
  test: ^0.12.20+12
